db_user="tom"  # Your MySQL username
db_passwd="user"  # Your MySQL password
db_name ="formatdb"  # Your MySQL database name

themes = [
        # Genre-based themes
        {'name': 'Action Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Action'"},
        {'name': 'Comedy Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Comedy'"},
        {'name': 'Drama Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Drama'"},
        {'name': 'Sci-Fi Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Sci-Fi'"},
        {'name': 'Romantic Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Romance'"},
        {'name': 'Horror Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Horror'"},
        {'name': 'Thriller Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Thriller'"},
        {'name': 'Animated Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Animation'"},
        {'name': 'Family Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Family'"},
        {'name': 'Adventure Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Adventure'"},
        {'name': 'Crime Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Crime'"},
        {'name': 'Fantasy Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Fantasy'"},
        {'name': 'Mystery Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Mystery'"},
        {'name': 'Documentary Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Documentary'"},
        {'name': 'Biographical Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Biography'"},
        {'name': 'War Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'War'"},
        {'name': 'Western Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Western'"},
        {'name': 'Musical Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Musical'"},
        {'name': 'Sport Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Sport'"},
        {'name': 'History Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'History'"},
        # Decade-based themes
        {'name': 'Movies from the 1950s', 'sql_condition': "WHERE m.release_date BETWEEN 1950 AND 1959"},
        {'name': 'Movies from the 1960s', 'sql_condition': "WHERE m.release_date BETWEEN 1960 AND 1969"},
        {'name': 'Movies from the 1970s', 'sql_condition': "WHERE m.release_date BETWEEN 1970 AND 1979"},
        {'name': 'Movies from the 1980s', 'sql_condition': "WHERE m.release_date BETWEEN 1980 AND 1989"},
        {'name': 'Movies from the 1990s', 'sql_condition': "WHERE m.release_date BETWEEN 1990 AND 1999"},
        {'name': 'Movies from the 2000s', 'sql_condition': "WHERE m.release_date BETWEEN 2000 AND 2009"},
        {'name': 'Movies from the 2010s', 'sql_condition': "WHERE m.release_date BETWEEN 2010 AND 2019"},
        # Director-based themes
        {'name': 'Movies by Steven Spielberg', 'sql_condition': "JOIN crew cr ON m.movie_id = cr.movie_id WHERE cr.name = 'Steven Spielberg' AND cr.job = 'Director'"},
        {'name': 'Movies by Martin Scorsese', 'sql_condition': "JOIN crew cr ON m.movie_id = cr.movie_id WHERE cr.name = 'Martin Scorsese' AND cr.job = 'Director'"},
        {'name': 'Movies by Quentin Tarantino', 'sql_condition': "JOIN crew cr ON m.movie_id = cr.movie_id WHERE cr.name = 'Quentin Tarantino' AND cr.job = 'Director'"},
        {'name': 'Movies by Alfred Hitchcock', 'sql_condition': "JOIN crew cr ON m.movie_id = cr.movie_id WHERE cr.name = 'Alfred Hitchcock' AND cr.job = 'Director'"},
        {'name': 'Movies by Christopher Nolan', 'sql_condition': "JOIN crew cr ON m.movie_id = cr.movie_id WHERE cr.name = 'Christopher Nolan' AND cr.job = 'Director'"},
        # Award-based themes
        {'name': 'Oscar-Winning Movies', 'sql_condition': "WHERE m.awards LIKE '%Oscar%'"},
        {'name': 'Critically Acclaimed Movies', 'sql_condition': "WHERE m.metascore > 80"},
        {'name': 'Top Rated Movies', 'sql_condition': "WHERE m.imdb_rating > 8.5"},
        # Mixed themes
        {'name': 'Romantic Comedies', 'sql_condition': "JOIN genres g1 ON m.movie_id = g1.movie_id JOIN genres g2 ON m.movie_id = g2.movie_id WHERE g1.genre = 'Romance' AND g2.genre = 'Comedy'"},
        {'name': 'Science Fiction Classics', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Sci-Fi' AND m.release_date < 1980"},
        {'name': 'Animated Disney Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Animation' AND m.production_company LIKE '%Disney%'"},
        {'name': 'Pixar Animation Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Animation' AND m.production_company LIKE '%Pixar%'"},
        {'name': 'Blockbuster Movies', 'sql_condition': "WHERE m.revenue > 100000000"},
        {'name': 'Foreign Language Films', 'sql_condition': "WHERE m.language != 'English'"},
        {'name': 'Film Noir Classics', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Film-Noir'"},
        {'name': 'Superhero Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Action' AND (m.title LIKE '%Superman%' OR m.title LIKE '%Batman%' OR m.title LIKE '%Spider-Man%' OR m.title LIKE '%Avengers%')"},
        {'name': 'Epic Historical Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'History' AND m.runtime > 150"},
        {'name': 'Classic Musicals', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Musical' AND m.release_date < 1970"},
        {'name': 'Psychological Thrillers', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Thriller' AND m.imdb_rating > 7.5"},
        {'name': 'Cult Classic Movies', 'sql_condition': "WHERE m.imdb_votes BETWEEN 50000 AND 200000 AND m.imdb_rating > 7.0"},
        {'name': 'Award-Winning Documentaries', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Documentary' AND m.awards LIKE '%Oscar%'"},
        {'name': 'Black and White Classics', 'sql_condition': "WHERE m.color_info = 'Black and White' AND m.release_date < 1965"},
        {'name': 'Coming-of-Age Films', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Drama' AND m.plot_keywords LIKE '%coming of age%'"},
        {'name': 'Movies Based on True Stories', 'sql_condition': "WHERE m.plot_keywords LIKE '%based on true story%' OR m.plot_keywords LIKE '%true events%'"},
        {'name': 'Feel-Good Movies', 'sql_condition': "WHERE m.plot_keywords LIKE '%feel good%' OR m.genre LIKE '%Family%'"},
        {'name': 'Independent Films', 'sql_condition': "WHERE m.budget < 5000000"},
        {'name': 'Movies Set in Space', 'sql_condition': "WHERE m.plot_keywords LIKE '%space%' OR m.plot_keywords LIKE '%astronaut%'"},
        {'name': 'Time Travel Movies', 'sql_condition': "WHERE m.plot_keywords LIKE '%time travel%'"},
        {'name': 'Movies with Twist Endings', 'sql_condition': "WHERE m.plot_keywords LIKE '%twist ending%'"},
        {'name': 'Zombie Movies', 'sql_condition': "WHERE m.plot_keywords LIKE '%zombie%'"},
        {'name': 'Movies About Artificial Intelligence', 'sql_condition': "WHERE m.plot_keywords LIKE '%artificial intelligence%' OR m.plot_keywords LIKE '%A.I.%'"},
        {'name': 'Heist Movies', 'sql_condition': "WHERE m.plot_keywords LIKE '%heist%' OR m.plot_keywords LIKE '%robbery%'"},
        {'name': 'Inspirational Sports Movies', 'sql_condition': "JOIN genres g ON m.movie_id = g.movie_id WHERE g.genre = 'Sport' AND m.plot_keywords LIKE '%inspirational%'"},
        # Add more themes as needed up to 40+
    ]